services:
  db:
    image: postgres:16-alpine
    container_name: chii2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxc
      POSTGRES_DB: chii_db
      # POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: