services:
  db:
    image: postgres:16-alpine 
    container_name: chii2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: zxc 
      POSTGRES_DB: chii_db 
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=en_US.utf8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: chii2_minio_storage
    restart: always
    ports:
      - "9000:9000"  
      - "9001:9001"  
    environment:
      
      MINIO_ROOT_USER: chii2accesskey 
      MINIO_ROOT_PASSWORD: chii2secretkeyVERYSTRONG 
      MINIO_DEFAULT_BUCKETS: "user-anomalies" 
                                            
    volumes:
      - minio_data:/data 
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data: