"""Add/Update anomaly table for single frames

Revision ID: 181f7b2e4da2
Revises: 9d293720475c
Create Date: 2025-05-28 21:07:46.914214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181f7b2e4da2'
down_revision = '9d293720475c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_detected', sa.DateTime(), nullable=False),
    sa.Column('source_type', sa.String(length=10), nullable=False),
    sa.Column('source_identifier', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('detected_class', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomalies')
    # ### end Alembic commands ###
